services:
  feet-bot:
    image: ghcr.io/theinternetuse7/feet-bot:latest
    pull_policy: always
    container_name: feet-bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
      - feet-data:/app/data
volumes:
  feet-data:
    name: feet-data
